name: Loading check - testing with v5
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  merge_group:
  schedule:
    - cron: 0 23 * * *
env:
  GO_VERSION: '1.22'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
    - name: Setup tar default options
      shell: bash
      run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV

    - name: building defsec
      run: echo "Building defsec..."

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
 