name: Loading check self hosted windows

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  merge_group:
  schedule:
    - cron: '0 23 * * *'

env:
  GO_VERSION: '1.22'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ self-hosted ]
    steps:
      - name: building defsec
        run: echo "Building defsec..."

      - uses: actions/checkout@v4

      - uses: lmvysakh/setup-go@test_515
      # - uses:  actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Display Go version
        run: go version
