name: Loading check for windows self hosted
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  merge_group:
  schedule:
    - cron: 0 23 * * *
env:
  GO_VERSION: '1.22'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ self-hosted ]
    steps:
    # - name: Setup tar default options (Linux/macOS only)
    #   if: matrix.os != 'windows-latest'
    #   shell: bash
    #   run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV

    # - name: Setup tar default options (Windows)
    #   if: matrix.os == 'windows-latest'
    #   shell: pwsh
    #   run: echo "TAR_OPTIONS=--skip-old-files" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Building defsec
      run: echo "Building defsec..."

    - uses: actions/checkout@v4

    - name: Setup Go
      uses: lmvysakh/setup-go@test_515
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: go mod tidy (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "Run 'go mod tidy' and push it"
          exit 1
        fi

    - name: go mod tidy (Windows only)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        go mod tidy
        $status = git status --porcelain
        if ($status) {
          Write-Host "Run 'go mod tidy' and push it"
          exit 1
        }

    - name: Run non-localstack tests (Linux/macOS only)
      if: matrix.os != 'ubuntu-latest' && matrix.os != 'windows-latest'
      run: make test-no-localstack
      shell: bash

    - name: Run non-localstack tests (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        make test-no-localstack

    - name: Run full tests (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: make test
      shell: bash
