name: Loading check self hosted windows
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  merge_group:
  schedule:
    - cron: 0 23 * * *
env:
  GO_VERSION: '1.22'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ self-hosted ]
    steps:

      - name: building defsec
        run: echo "Building defsec..."

      - name: Ensure D drive is available (Windows only)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          if (-not (Test-Path 'D:\')) {
            Write-Host "D: drive not found. Creating virtual drive as D:."
            $drivePath = "$env:TEMP\virtual-d-drive"
            New-Item -ItemType Directory -Force -Path $drivePath | Out-Null
            subst D: $drivePath
            Write-Host "Created virtual D: drive at $drivePath"
          } else {
            Write-Host "D: drive already exists."
          }

      - uses: actions/checkout@v4

      - uses: antontroshin/setup-go@windows-go-mod-cache
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: go mod tidy
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "Run 'go mod tidy' and push it"
            exit 1
          fi
      - name: Run non-localstack tests
        if: matrix.os != 'ubuntu-latest'
        run: make test-no-localstack
        shell: bash

      - name: Run full tests
        if: matrix.os == 'ubuntu-latest'
        run: make test
        shell: bash
