name: Loading check self hosted windows

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  merge_group:

env:
  GO_VERSION: '1.22'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ self-hosted ]
    steps:

      - name: building defsec
        run: echo "Building defsec..."

      - uses: actions/checkout@v5

      - name: Clean Go cache (may need admin rights)
        run: |
          if (Test-Path "C:\Users\Vysakh\go\pkg\mod") { Remove-Item -Recurse -Force "C:\Users\Vysakh\go\pkg\mod" }
          if (Test-Path "C:\Users\Vysakh\AppData\Local\go-build") { Remove-Item -Recurse -Force "C:\Users\Vysakh\AppData\Local\go-build" }
        shell: powershell

      - name: Create Go build cache directory (only if not exists)
        run: |
          if (!(Test-Path -Path "C:\Users\Vysakh\AppData\Local\go-build")) {
            mkdir "C:\Users\Vysakh\AppData\Local\go-build"
          }
        shell: powershell

      # - uses: actions/setup-go@v6
      - uses: lmvysakh/setup-go@dummyfix_ddrive
      # - uses: lmvysakh/setup-go@ddrive_error_fix
      # - uses: lmvysakh/setup-go@windows_runner_cache_load_fix
        with:
          go-version: ${{ env.GO_VERSION }}
            
 
   
  