name: Loading check
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  merge_group:
  schedule:
    - cron: 0 23 * * *
env:
  GO_VERSION: '1.22'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
    - name: Setup tar default options
      shell: bash
      run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV

    - name: building defsec
      run: echo "Building defsec..."

    - uses: actions/checkout@v4

    - uses: lmvysakh/setup-go@test_515
      with:
        go-version: ${{ env.GO_VERSION }}
   
    - name: Display Go version
      run: go version
   
 